### ISSUE TITLE
Stroke border?

### ISSUE THREAD

**Issue by rwzdoorn** [heestand-xyz/PolyKit#2]
Hi,

Love the simplicity of PolyKit! I'm currently experimenting with the package but can't figure out how to add a stroke (with line width + color). I already tried `.border` but this creates a rectangle border. Workaround for now is duplicating the view, make it bigger and use ZStack.

**Comment by heestand-xyz** [comment]
The old `Poly` was a view, the new `Polygon` is a shape and have stroke support.

**Comment by heestand-xyz** [comment]
Also check out [Shapes](https://github.com/heestand-xyz/Shapes)
